### ISSUE TITLE
Remove the YAML file 

### ISSUE THREAD

**Issue by sandertan** [thehyve/cbioportal-staging#14]
The current design centers around a YAML file that contains all files to be transferred. I think this overcomplicates the process for the user. It would be easier if an input directory is sufficient.

If the YAML file is used to signal that data is ready to be transformed, I think this design should be reconsidered. A far easier approach would be to signal the app with a command that the data is ready to be loaded. Or alternatively, check for the existence of the YAML file for signaling, but its contents should in that case not matter.

**Comment by oplantalech** [comment]
@sandertan I believe we have solved that issue now.
