### ISSUE TITLE
portal.home is missing in the application.properties

### ISSUE THREAD

**Issue by rnugraha** [thehyve/cbioportal-staging#16]
portal.home looks like needs to be defined but it's not mentioned in the application.properties.EXAMPLE

**Comment by oplantalech** [comment]
@rnugraha I added a commit in the master branch fixing this. However, usually you won't need this variable as it is defined by default with the value `PORTAL_HOME` from the environment (which is a requirement to load studies to cBioPortal locally). However, it is nice to have it documented in the `application.properties.EXAMPLE` so I've done that.
