### ISSUE TITLE
App fails because FtpResourceProvider is used on local files

### ISSUE THREAD

**Issue by SRodenburg** [thehyve/cbioportal-staging#40]
When using the flag `transformation.metafile.check=true` (also the default), the program will check the local resources (that it first downloads), to see if any already contain metafiles.

This causes a crash (which is by the way very cryptic and hard to inspect because of the many aspecific catches).

```
cbio-staging            | 2020-10-22 13:40:09.582  INFO 21 --- [   scheduling-1] org.cbioportal.staging.etl.Extractor     : Extractor step finished
cbio-staging            | 2020-10-22 13:40:09.771 ERROR 21 --- [   scheduling-1] o.c.staging.etl.ETLProcessRunner         : An error occurred during the transformation step. Error found: org.cbioportal.staging.exceptions.ReporterException: org.cbioportal.staging.exceptions.ResourceCollectionException: Could not read from remote directory:
cbio-staging            | 2020-10-22 13:40:09.875  INFO 21 --- [   scheduling-1] o.c.staging.etl.ETLProcessRunner         : Closing socket / releasing lock
```

The logs show:
```
An error occurred during the transformation step. Error found:
Stacktrace:
org.cbioportal.staging.exceptions.ReporterException: org.cbioportal.staging.exceptions.ResourceCollectionException: Could not read from remote directory: <br/>
        at org.cbioportal.staging.etl.Transformer.transform(Transformer.java:89)<br/>
        at org.cbioportal.staging.etl.ETLProcessRunner.run(ETLProcessRunner.java:124)<br/>
        at org.cbioportal.staging.app.ScheduledScanner.scan(ScheduledScanner.java:100)<br/>
```

The error originates from this line: 
https://github.com/thehyve/cbioportal-staging/blob/d1ab2c4c8b50dd74043b25b9bca582a6e6d6c6eb/src/main/java/org/cbioportal/staging/etl/Transformer.java#L121 

Somehow it uses the `FtpResourceProvider` instead of the `FileSystemResourceProvider`.

**Comment by pvannierop** [comment]
@SRodenburg Ah nice catch. I have applied a patch. Can you try the branch `fix_resource_filtering` to see whether the problem is gone?

**Comment by SRodenburg** [comment]
@pvannierop can u rebase this branch on master? There were some improvements there that I'd like to see integrated in this branch.
